### ISSUE TITLE
태그 표시 부분에서 오류 발생

### ISSUE THREAD

**Issue by rzglitch** [calvinsnax/rx-flextagram#10]
![tag_php8](https://user-images.githubusercontent.com/60917154/119341677-0995da80-bccf-11eb-8143-732fbfbb9dd6.png)

PHP 8.0.6 라이믹스 최신버전 입니다.

일단 tag_list가 null이면 빈 array로 출력하게 해서 해결했는데

이게 PHP 8.0 문제인지 라이믹스 버전에 따른 문제인지 모르겠네요.

**Comment by calvinsnax** [comment]
PHP 8.0은 써보지도 못해서 정확하진 않지만 아무래도 8.0에서 타입 관련 규칙이 강해져서 그런게 아닐까 싶습니다.

`{@ $tag_list = $oDocument->get('tag_list') ?? array() }`

해결하신 방법이 이게 맞나요? 임시로라도 개선 코드를 반영해놓으려고 합니다.

**Comment by rzglitch** [comment]
네 맞습니다. 그렇게 하면 되더군요.
