### ISSUE TITLE
article-toolbar__comment.js not found 에러가 발생합니다.

### ISSUE THREAD

**Issue by wookho** [calvinsnax/rx-flextagram#11]
/modules/board/skins/rx-flextagram/components/article/article-toolbar/article-toolbar__comment.js

위 경로에 파일이 없다고 에러가 뜹니다.
해당 경로에 파일은 존재하지 않고 있네요.

**Comment by calvinsnax** [comment]
정말로 해당 경로에 파일이 없는게 아닐까요? article-toolbar__comment.html 내에서 같은 폴더 내에 존재하는 article-toolbar__comment.js 파일을 불러오는 부분이 있습니다. 해당 파일들이 article-toolbar 폴더에 함께 존재하는지 확인해주세요.

**Comment by wookho** [comment]
@calvinsnax 
https://github.com/calvinsnax/rx-flextagram/tree/main/modules/board/skins/rx-flextagram/components/article/article-toolbar
해당 경로에 파일 자체가 없어요.

**Comment by calvinsnax** [comment]
제가 잘못 확인했네요. comment.js 파일은 toolbar.js 파일에 합쳐졌기 때문에 load 부분을 제거하셔도 됩니다^^
