### ISSUE TITLE
버그를 한가지 제보하고 싶습니다.

### ISSUE THREAD

**Issue by juckdo** [calvinsnax/rx-flextagram#3]
1. 게시판 _header.html 파일과 _footer.html 파일이 없어서
message.html과 input_password_form.html 호출이 필요한 상황이 생길 시 디자인이 깨지는 문제점이 있습니다.

2. 게시판 글 작성 시 임시 저장, 불러오기 버튼을 누르면
제목 값은 필수입니다, 내용 값은 필수입니다와 같은 대화상자가 뜹니다.

3. Content 위젯스킨에 캐시 적용 시(위젯자체캐시 슈퍼캐시 둘다해당됨)
ul 항목 앞에 점이 뜨면서 디자인이 깨지는 문제점이 있습니다.

이슈 내용을 수정하다 보니 한가지가 아니라 세가지가 되어버렸습니다.
써보니 이 세가지 외에 큰 문제점은 없는 것 같습니다.
좋은 레이아웃 좋은 뜻으로 무료배포 해주시는 큰 결정 해주셔서 대단히 감사드립니다.

**Comment by calvinsnax** [comment]
제보 감사합니다. 혹시 위젯 캐시 사용 시 목록 앞에 점이 붙는 이슈 외에 또 다른 문제점이 있다면 제보 부탁드립니다. 감사합니다.
