### ISSUE TITLE
게시글 추천과 추천수 표시는 우선 가능해야 할 것 같습니다.

### ISSUE THREAD

**Issue by wookho** [calvinsnax/rx-flextagram#8]
To do에 
목록에서 새로고침 없는 좋아요, 댓글 쓰기, 스크랩 구현

항목이 있어서 제보를 미루고 있었는데 새로고침 없이 가능한 부분과 기능 자체가 작동하는 것은 별개인 것 같아 제보드립니다.
현재 목록에서 추천을 해도 추천이 되지 않아서 문제가 될 것 같습니다.

추천시 표시 안되는 문제는 제가 목록 설정에 추천수를 포함하지 않아서 생기는 문제였네요.

목록 설정에 추천수를 포함 한 후 목록에서 추천이 되는지도 확인해보겠습니다.

지금 상황을 다시 유추해 보니 목록에서 추천 자체가 To do 에 있는게 아닌가 하는 생각이 드네요.
본문의 이게시글을... 통해서 추천을 해야 하는 시점일 것 같긴 합니다.

**Comment by calvinsnax** [comment]
목록에 표시되는 추천은 디자인만 SNS의 그것과 흡사할 뿐 실제로는 아무런 기능도 없습니다. 아예 누르라고 만들어준 것이 아니에요. 따라서 Todo 리스트에 있는 것이구요. 제가 못하도라도 누군가는 만들 수 있을 것이라 생각하여 디자인을 가능성있게 만들어두었습니디. 그냥 SNS 스러운 감성을 살려보려고 한 것도 있구요. 실제 새로고침없는 추천 기능은 본문 하단 화면을 따라오는 툴바를 통해 가능합니다. 혹 본문 추천 기능 또한 작동이 안된다는 말씀이신지는 잘 모르겠네요. 해당 이슈는 잘못 이해하고 계셨던 것으로 판단하여 Close하도록 하겠습니다.
